apiVersion: v1
kind: Template
metadata:
  name: msr-openshift-template

parameters:
- name: APPLICATION_NAME
  description: the application name
  value: mah-msr-helloworld-api
  required: true
- name: IMAGE_TAG
  description: the image tag of the MSR with custom packages
  value: "1.0"
  required: true  
- name: CLUSTER_BASE_URL
  description: the base URL of this OpenShift cluster
  value: apps.ocp1.eur.ad.sag
  required: true

labels:
  app: ${APPLICATION_NAME}
  app.kubernetes.io/component: ${APPLICATION_NAME}
  app.kubernetes.io/instance: ${APPLICATION_NAME}
  template: msr-template


objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 5555-tcp
      port: 5555
      protocol: TCP
      targetPort: 5555
    - name: 9072-tcp
      port: 9072
      protocol: TCP
      targetPort: 9072
    - name: 9999-tcp
      port: 9999
      protocol: TCP
      targetPort: 9999
    selector:
      app: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
    
    
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: ${APPLICATION_NAME}
    replicas: 1
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: madhugupta99/${APPLICATION_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
          - containerPort: 5555
            protocol: TCP
          - containerPort: 9072
            protocol: TCP
          - containerPort: 9999
            protocol: TCP
          resources:
            requests:
              memory: 4G
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File                     

      
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    host: ${APPLICATION_NAME}.${CLUSTER_BASE_URL}
    port:
      targetPort: 5555-tcp
    subdomain: ""
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None
    



